# Default values for guestbookredismaster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
service:
  type: NodePort

redismaster:
  repository: gcr.io/kubernetes-e2e-test-images/redis
  tag: "1.0"
  pullPolicy: IfNotPresent
