apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: engineer-role
  namespace: default
rules:
- apiGroups:
  - core
  resources:
  - pods
  - configmaps
  - deployments
  verbs:
  - get
  - list
  - watch
  - delete
  - create
  - update
  - patch
