# Default values for guestbookredisslave.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

service:
  type: ClusterIP
redisslave:
  repository: gcr.io/google_samples/gb-redisslave
  tag: v3
  pullPolicy: IfNotPresent
